# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-argument-parser" = "11igj86hrm83813m01mxgqxalcpbj5y419pw31z4wy43ip3bj6mq";
    "swift-atomics" = "0rzq9klikwm4jv9y0wqb2wajlv6nlcyjgg5bvf35209h6l2gz38y";
    "swift-collections" = "0ymxq7flzkhjxsyv4pjmlf86bvb93rhgkm2mlvsbb0lxz6729h2k";
    "swift-distributed-tracing" = "0p2xinw822znyh274bbpigznlvzf1wkjfjhgsvb868lkwj791r3q";
    "swift-docc-plugin" = "1mn2xm5m41dav8c1ly8cygz2p8ykrhsi6s4b1d9yn9cysdfyacqn";
    "swift-docc-symbolkit" = "14w37wzbx1mygfwm4iv0ypj120n1axhk627rg5a7v8j0ln511r7s";
    "swift-http-types" = "1r819avswd5zl76kkjc0d7jczcwwna5fa9d5qw6h4hhqpv03r5m5";
    "swift-log" = "1045r1nxrz86cmxygd5dms06ybgyhqfzlv01645x96m2ial92i79";
    "swift-nio" = "0j05dz9y8d7q9xc1rsw3p4xny3bsxwignammphix5hh02hxymxx3";
    "swift-nio-extras" = "0qlgh5znji1zmygfb6ym7ldm7nzqq8grmhdmsjib0rpgmz40zssl";
    "swift-nio-http2" = "06468kyfzh2gwsbk1wkkiv1rf4nhlcszjdiibb0pf2cv5dnrm4pr";
    "swift-nio-ssl" = "0iab2kr1klbdhhpy46rfqwnf1r27qnjafpm1c4f8d051vzhlk0j8";
    "swift-nio-transport-services" = "0xi25hs1g7479yr24vx78s7di9zd85wl2h8xsf3pxi03y22rkyli";
    "swift-protobuf" = "03cry5cqp9brrrsqsklvlzm3avc9bbidaf9v0asp0q84l40rg0sw";
    "swift-service-context" = "1f4wlirpymi9w7an5ncalxbmpkyrld2fp4nchvyl5pz09wcdk96m";
    "swift-system" = "0g24vjxixzhpk4mjmq6zsh8wjkl631msg0v3hgyh7bf45nf5wzd8";
  };
}
